In [10]:
%load_ext autoreload
%autoreload 2
# the imported files are updated each time a cell is executed (good if functions in py files are added and modified)

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import sys
import os

from scipy.spatial.transform import Rotation as R
from pyswarms.single.global_best import GlobalBestPSO

sys.path.insert(0, '..')
sys.path.insert(0, '...')

from Python.LMC_util import plotLMC, make_LMC, check_LMC_Hand_visibility, make_hand_poses
from Python.plotUtil import plot_hand

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
current_dir = os.getcwd()
file_data = "Static.txt"

filename = os.path.join(current_dir, file_data)
dataFile = pd.read_csv(filename,index_col=False,sep=r',|\t', engine='python')
dataFile = dataFile.replace('\t','', regex=True)

# to numpy
posDatas_ = dataFile.to_numpy()
posDatas = posDatas_[:, [4, 5, 6] + [13+i for i in range(94-13)]] # cut away unnecessary data
posDatas = posDatas.reshape(posDatas.shape[0], int(posDatas.shape[1]/3), 3)
posDatas = posDatas[:, [i for i in range(posDatas.shape[1]) if i not in [0, 2, 3, 8, 13, 18]]] # cut away unnecessary markers
# rotate dta such that z points up
frame = (R.from_euler('XYZ', [90, 0, 0], degrees=True).as_matrix().squeeze() @ posDatas[0].T).T
print(frame.shape)

fig = go.Figure()
plot_hand(fig, frame, names=np.arange(0, frame.shape[0]))
fig.show()

(22, 3)


# Check finger visibility for a single frame from a given number of LMCs

In [12]:
from Python.LMC_util import fingers_idx_LMC

# Input parameter
finger_radius = 10 # mm

# LMC settings
num_LMC = 1
LMC_H = 600 # mm
LMC_alpha1 = (180-150) / 2 * np.pi / 180
LMC_alpha2 = (180-120) / 2 * np.pi / 180
deviceColor = ['orange', 'blue', 'green', 'black']
deviceLabel = ['Device {}'.format(i) for i in range(1, num_LMC+1)]
LMC_positions = np.array([0,0,0]*num_LMC).reshape(num_LMC, 3) # in mm
LMC_orientations = np.array([0,0,0]*num_LMC).reshape(num_LMC, 3) # in deg
LMCs = [make_LMC(LMC_loc=LMC_positions[i], LMC_orient=LMC_orientations[i], LMC_H=LMC_H, LMC_alpha1=LMC_alpha1, LMC_alpha2=LMC_alpha2) for i in range(num_LMC)]

# input data
frames = np.array([frame]) # one row for a single frame of each LMC
#transform data in global frame
for lm, LMC in enumerate(LMCs):
    LMC_orient = R.from_euler('xyz', [*LMC[1]], degrees=True).as_matrix().squeeze()
    frames[lm, :] = (LMC_orient @ (frames[lm, :] + LMC[0]).T).T 

# get data for ray tracing
handMarkers, palmMarkers, palmPlnNormals, palmCentroids, fingers, forearm_vecs = make_hand_poses(frames)   
occlusions = np.zeros([num_LMC, 5])
fig = go.Figure()
for lm, LMC in enumerate(LMCs):
    occlusions_, _ = check_LMC_Hand_visibility(LMC, pos_markers=handMarkers[lm], fingers_idx=fingers_idx_LMC, finger_lines=fingers[lm], 
                                                finger_radius=finger_radius, palm_plane_normal=palmPlnNormals[lm], 
                                                palm_centroid=palmCentroids[lm], palm_markers=palmMarkers[lm], forearm_vec=forearm_vecs[lm],
                                                fig = fig, verbose=1)
    print(occlusions_)
    occlusions[lm] = occlusions_[2:]

print(occlusions) # 0: thumb, 4:pinky


for lm, LMC in enumerate(LMCs):
    fig = plot_hand(fig, frames[lm], color=deviceColor[lm], names=np.arange(0, frames[lm].shape[0]))
    fig = plotLMC(fig, LMC, color=deviceColor[lm], name=deviceLabel[lm], scale=1)
fig.show()

___________________________________
Finger  0
___________________________________
Finger  1
___________________________________
Finger  2
___________________________________
Finger  3
___________________________________
Finger  4
[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]]


# Optimize LMC position for Recorded leap data

In [13]:
from Python.optimization import PSO_Objective, plotPSOResult
from Python.LMC_util import fingers_idx_LMC

# Input parameter    
finger_radius = 10 # mm

# LMC settings
LMC_H = 600 # mm
num_LMC = 4
LMC_alpha1 = (180-150) / 2 * np.pi / 180
LMC_alpha2 = (180-120) / 2 * np.pi / 180
LMC_positions = np.array([0,0,0]*num_LMC).reshape(num_LMC, 3) # in mm
LMC_orientations = np.array([0,0,0]*num_LMC).reshape(num_LMC, 3) # in deg
LMCs = [make_LMC(LMC_loc=LMC_positions[i], LMC_orient=LMC_orientations[i], LMC_H=LMC_H, LMC_alpha1=LMC_alpha1, LMC_alpha2=LMC_alpha2) for i in range(num_LMC)]

# input data
'''
  CAREFUL! The optimizer does not work for a single pose! the more the better
          if only a single pose is available then it was to be stacked a few times. e.g 10 times 
          this is caused by the metric that uses an exposnential norm with the number of poses
'''
frames = np.array([frame]*10) # one row for each frame (if the data is from multiple LMC then they are just flattened such that frames.shape = (num_recordedposes*num_LMC, num_markers, 3)
# transform data in global frame
for lm, LMC in enumerate(LMCs):
    LMC_orient = R.from_euler('xyz', [*LMC[1]], degrees=True).as_matrix().squeeze()
    frames[lm, :] = (LMC_orient @ (frames[lm, :] + LMC[0]).T).T 

# get data for ray tracing
print(frames.shape)
handMarkers, palmMarkers, palmPlnNormals, palmCentroids, fingers, forearm_vecs = make_hand_poses(frames)   
print(handMarkers.shape)
data = [handMarkers, palmMarkers, palmPlnNormals, palmCentroids, fingers, forearm_vecs]

# instatiate the optimizer
options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
x_max = np.array([1, 1, 1, 1]*num_LMC)
x_min = np.array([-1, -1, -1, -1]*num_LMC)
parameter_mult = np.array([1000, 1000, 90, 180]*num_LMC) 
bounds = (x_min, x_max)

n_particles = 30
num_iterations = 100
args = (data, finger_radius, fingers_idx_LMC, num_LMC, LMC_H, LMC_alpha1, LMC_alpha2, parameter_mult)
optimizer = GlobalBestPSO(n_particles=n_particles, dimensions=4*num_LMC, options=options, bounds=bounds)
# pos is the optimized LMC location and orientation as
'''
  pos = np.array([x, y, xrot, zrot]*num_LMC) / parameter_mult 
  this means pos needs to be multiplied with parameter_mult to get the position in mm and orientation in deg
'''
# a good cost is smaller than 1e-3
cost, pos = optimizer.optimize(PSO_Objective, num_iterations, args=args)
plotPSOResult(pos, args)

2024-08-28 17:01:50,343 - pyswarms.single.global_best - INFO - Optimize for 100 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}


(10, 22, 3)
(10, 22, 3)


pyswarms.single.global_best: 100%|██████████|100/100, best_cost=0   
2024-08-28 17:07:22,086 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.0, best pos: [ 0.19718682  0.08902858  0.06332609  0.13283798  0.12871504  0.18848024
 -0.22142844  0.35550357  0.15188389  0.36851435  0.34696232  0.41174164
 -0.00238062  0.01775739  0.33624525  0.44922393]


_________________________________
POS:  0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
Best LMC:  [0 1 2 3]
_________________________________
POS:  1
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
Best LMC:  [0 1 2 3]
_________________________________
POS:  2
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
Best LMC:  [0 1 2 3]
_________________________________
POS:  3
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
Best LMC:  [0 1 2 3]
_________________________________
POS:  4
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
Best LMC:  [0 1 2 3]
_________________________________
POS:  5
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
Best LMC:  [0 1 2 3]
_________________________________
POS:  6
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 1.] 5.0
[1. 1. 1. 1. 